"""Report generation — generate professional security reports from findings."""

from __future__ import annotations

import json
import time
from typing import Any

from loguru import logger

from ..core.db import execute as db_execute
from ..tools.base import BaseTool, ToolResult, ToolSpec, RiskLevel


def _generate_markdown_report(findings: list[dict], lab: dict | None = None) -> str:
    """Generate a professional markdown security report."""
    now_str = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    total = len(findings)
    critical = sum(1 for f in findings if f.get("severity") == "critical")
    high = sum(1 for f in findings if f.get("severity") == "high")
    medium = sum(1 for f in findings if f.get("severity") == "medium")
    low = sum(1 for f in findings if f.get("severity") == "low")
    info = sum(1 for f in findings if f.get("severity") == "info")

    lines = [
        "# NEXORA Security Assessment Report",
        "",
        f"**Generated:** {now_str}",
    ]

    if lab:
        lines.extend([
            f"**Lab:** {lab.get('name', 'N/A')}",
            f"**Target:** {lab.get('target', 'N/A')}",
            f"**Scope:** {lab.get('scope', 'N/A')}",
            f"**Status:** {lab.get('status', 'N/A')}",
        ])

    lines.extend([
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"This report documents **{total}** security finding(s) identified during the assessment.",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical | {critical} |",
        f"| 🟠 High | {high} |",
        f"| 🟡 Medium | {medium} |",
        f"| 🔵 Low | {low} |",
        f"| ⚪ Info | {info} |",
        "",
    ])

    # Severity-ordered findings
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_findings = sorted(findings, key=lambda f: severity_order.get(f.get("severity", "info"), 5))

    if sorted_findings:
        lines.extend(["## Findings", ""])

        for i, f in enumerate(sorted_findings, 1):
            severity = f.get("severity", "info")
            icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}.get(severity, "⚪")
            lines.extend([
                f"### {i}. {icon} {f.get('title', 'Untitled')}",
                "",
                f"- **Severity:** {severity.upper()}",
                f"- **Status:** {f.get('status', 'open')}",
                f"- **Affected Asset:** {f.get('affected_asset', 'N/A')}",
                f"- **Category:** {f.get('category', 'general')}",
                "",
            ])

            if f.get("description"):
                lines.extend(["**Description:**", f.get("description", ""), ""])
            if f.get("evidence"):
                lines.extend(["**Evidence:**", "```", f.get("evidence", ""), "```", ""])
            if f.get("impact"):
                lines.extend(["**Impact:**", f.get("impact", ""), ""])
            if f.get("reproduction"):
                lines.extend(["**Reproduction Steps:**", f.get("reproduction", ""), ""])
            if f.get("remediation"):
                lines.extend(["**Remediation:**", f.get("remediation", ""), ""])

            lines.append("---")
            lines.append("")

    lines.extend([
        "## Methodology",
        "",
        "This assessment was conducted using NEXORA's automated security analysis tools.",
        "Findings were categorized by severity following industry-standard CVSS guidelines.",
        "",
        "## Disclaimer",
        "",
        "This report is provided for authorized security testing purposes only.",
        "The findings and recommendations should be validated by qualified security personnel.",
        "",
        f"*Report generated by NEXORA — {now_str}*",
    ])

    return "\n".join(lines)


def _generate_html_report(findings: list[dict], lab: dict | None = None) -> str:
    """Generate an HTML security report."""
    now_str = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    total = len(findings)
    critical = sum(1 for f in findings if f.get("severity") == "critical")
    high = sum(1 for f in findings if f.get("severity") == "high")
    medium = sum(1 for f in findings if f.get("severity") == "medium")

    lab_info = ""
    if lab:
        lab_info = f"""
        <p><strong>Lab:</strong> {lab.get('name', 'N/A')} |
        <strong>Target:</strong> {lab.get('target', 'N/A')} |
        <strong>Scope:</strong> {lab.get('scope', 'N/A')}</p>
        """

    findings_html = ""
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_findings = sorted(findings, key=lambda f: severity_order.get(f.get("severity", "info"), 5))

    for i, f in enumerate(sorted_findings, 1):
        sev = f.get("severity", "info")
        color = {"critical": "#ff3366", "high": "#ff8800", "medium": "#ffaa00", "low": "#00aaff", "info": "#888888"}.get(sev, "#888")
        findings_html += f"""
        <div class="finding" style="border-left: 4px solid {color}; padding: 12px; margin: 12px 0; background: #1a1a2e; border-radius: 4px;">
            <h3 style="color: {color}; margin: 0 0 8px 0;">{i}. {f.get('title', 'Untitled')}</h3>
            <p><strong>Severity:</strong> <span style="color: {color};">{sev.upper()}</span> |
            <strong>Status:</strong> {f.get('status', 'open')} |
            <strong>Asset:</strong> {f.get('affected_asset', 'N/A')}</p>
            <p>{f.get('description', '')}</p>
            {'<pre style="background: #0d1117; padding: 8px; border-radius: 4px; color: #c9d1d9;">' + f.get('evidence', '') + '</pre>' if f.get('evidence') else ''}
            {'<p><strong>Remediation:</strong> ' + f.get('remediation', '') + '</p>' if f.get('remediation') else ''}
        </div>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NEXORA Security Report</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background: #0a0e14; color: #e8f0f8; padding: 40px; max-width: 900px; margin: 0 auto; }}
        h1 {{ color: #00d4ff; border-bottom: 2px solid #00d4ff; padding-bottom: 10px; }}
        h2 {{ color: #00d4ff; margin-top: 30px; }}
        .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
        .stat {{ padding: 15px; background: #111820; border-radius: 8px; text-align: center; flex: 1; }}
        .stat .num {{ font-size: 24px; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 8px 12px; border: 1px solid #2a3a50; text-align: left; }}
        th {{ background: #111820; color: #00d4ff; }}
        pre {{ white-space: pre-wrap; word-wrap: break-word; }}
    </style>
</head>
<body>
    <h1>NEXORA Security Assessment Report</h1>
    <p><strong>Generated:</strong> {now_str}</p>
    {lab_info}
    <div class="summary">
        <div class="stat"><div class="num" style="color: #ff3366;">{critical}</div><div>Critical</div></div>
        <div class="stat"><div class="num" style="color: #ff8800;">{high}</div><div>High</div></div>
        <div class="stat"><div class="num" style="color: #ffaa00;">{medium}</div><div>Medium</div></div>
        <div class="stat"><div class="num">{total}</div><div>Total</div></div>
    </div>
    <h2>Findings</h2>
    {findings_html if findings_html else '<p>No findings documented.</p>'}
    <hr style="border-color: #2a3a50; margin-top: 40px;">
    <p style="color: #607890; font-size: 12px;">Report generated by NEXORA — {now_str}</p>
</body>
</html>"""


class GenerateReportTool(BaseTool):
    """Generate a security assessment report."""

    def spec(self) -> ToolSpec:
        return ToolSpec(
            name="security.reports.generate",
            description="Generate a security report (markdown or HTML) from findings.",
            category="security",
            risk_level=RiskLevel.SAFE,
            requires_confirmation=False,
            timeout=15.0,
            input_schema={
                "type": "object",
                "properties": {
                    "format": {
                        "type": "string",
                        "enum": ["markdown", "html"],
                        "description": "Report format",
                    },
                    "lab_id": {"type": "string", "description": "Include lab info"},
                    "severity_filter": {"type": "string", "description": "Only include findings of this severity"},
                    "save_path": {"type": "string", "description": "Save report to file path"},
                },
            },
        )

    async def execute(self, inputs: dict[str, Any]) -> ToolResult:
        from ..security.findings import _ensure_table as _ensure_findings_table
        await _ensure_findings_table()

        fmt = inputs.get("format", "markdown")
        severity = inputs.get("severity_filter")
        lab_id = inputs.get("lab_id")

        # Get findings
        query = "SELECT * FROM findings"
        params: list[Any] = []
        if severity:
            query += " WHERE severity = ?"
            params.append(severity)
        query += " ORDER BY created_at DESC"

        rows = await db_execute(query, tuple(params), fetch="all")
        findings = []
        for row in (rows or []):
            findings.append({
                "id": row["id"],
                "title": row["title"],
                "severity": row["severity"],
                "affected_asset": row["affected_asset"],
                "description": row["description"],
                "evidence": row["evidence"],
                "impact": row["impact"],
                "reproduction": row["reproduction"],
                "remediation": row["remediation"],
                "status": row["status"],
                "category": row["category"],
            })

        # Get lab info if requested
        lab = None
        if lab_id:
            lab_row = await db_execute("SELECT * FROM labs WHERE id = ?", (lab_id,), fetch="one")
            if lab_row:
                lab = {
                    "name": lab_row["name"],
                    "target": lab_row["target"],
                    "scope": lab_row["scope"],
                    "status": lab_row["status"],
                }

        # Generate report
        if fmt == "html":
            report = _generate_html_report(findings, lab)
        else:
            report = _generate_markdown_report(findings, lab)

        # Save to file if requested
        save_path = inputs.get("save_path")
        if save_path:
            import aiofiles
            async with aiofiles.open(save_path, "w") as f:
                await f.write(report)

        self.log_action("generate_report", details=f"fmt={fmt} findings={len(findings)}")
        return ToolResult(
            success=True,
            data={
                "format": fmt,
                "report": report,
                "findings_count": len(findings),
                "saved_to": save_path,
            },
        )


def register_report_tools(registry: Any) -> None:
    """Register report tools."""
    registry.register(GenerateReportTool())
